name: Java CI and Docker Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  APP_NAME: "projecterp"
  JAR_NAME: "projectERP-0.0.1-SNAPSHOT.jar"

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application
        run: |
          mvn clean package -DskipTests=false
          ls -la target/

      - name: Run tests
        run: mvn test
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          APP_NAME_LOWER=$(echo "${{ env.APP_NAME }}" | tr '[:upper:]' '[:lower:]')
          
          docker buildx build \
            --tag ghcr.io/$OWNER_LOWER/$APP_NAME_LOWER:latest \
            --tag ghcr.io/$OWNER_LOWER/$APP_NAME_LOWER:${{ github.sha }} \
            --push .
        shell: bash
         # --- NUEVOS PASOS PARA ACTUALIZAR MANIFESTOS ---
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: MaikHB/k8s_erp
          token: ${{ secrets.MANIFESTS_REPO_TOKEN }}
          path: manifests

      - name: Update image tag in YAML
        run: |
          cd manifests/manifiestos
          IMAGE_PATH="ghcr.io/maikhb/projecterp"
          NEW_TAG="${{ github.sha }}"
         
           # Actualizar el tag de la imagen en el deployment
          sed -i "s|${IMAGE_PATH}:.*|${IMAGE_PATH}:${NEW_TAG}|g" app-deployment.yaml

      - name: Commit & Push updated manifests
        run: |
          cd manifests
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push

